config/routes.rb
Rails.application.routes.draw do
  resources :estudia
  resources :trabajas
  resources :programas
  resources :aprendes
  resources :forums do
    resources :comments, only: [:create, :destroy]
  end
  
  devise_for :users
  get 'home/home'

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  #before_action :set_forum, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:new, :create, :edit, :destr
  load_and_authorize_resource

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @comments = @forum.comments
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    @forum.user = current_user
    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forum_params
      params.require(:forum).permit(:name, :description, :photo)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_with(model: forum, local: true) do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Photo</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td><%= forum.name %></td>
        <td><%= forum.description %></td>
        <td><%= forum.try(:photo) %></td>
        <td><%= forum.user.try(:email) %></td>
        <td><%= link_to 'Show', forum %></td>
        <% if user_signed_in? %> 
        <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
        <td><%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %> 
<%= link_to 'New post', new_forum_path %>
<% end %>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @forum.photo %>
</p>

</div>
<div class="row">
	<div class="col-md-4">
		<div class="well well-sm">
			<legend>Comentar:</legend>
			<%= form_with(model: [@forum, Comment.new], local: true, html: { class: 'form-horizontal' }) do |f| %>
				<div class="form-group">
					<div class="col-md-12">
						<%= f.text_area :content, placeholder: 'Escribe tu comentario aquí...', class: 'form-control' %>
					</div>
				</div>
				<%= f.submit 'Comentar', class: 'btn btn-primary' %>
			<% end %>
			  
		</div>
	</div>
	<div class="col-md-8">
		<% counter = 0 %>
		<% @comments.each do |comment| %>
			#<%= counter += 1 %>
			<div class="well well-sm">
				<strong><%= comment.user.email %>:</strong>
				<br>
				<%= comment.content %>
				<div class="text-right">
					<%= link_to 'Eliminar', forum_comment_path(@forum,comment), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar el Comentario?' }, class: 'btn btn-xs btn-danger' %>
				</div>
			</div>
		<% end %>
	</div>
</div>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>