config/routes.rb
Rails.application.routes.draw do
  resources :estudia
  resources :trabajas
  resources :programas
  resources :aprendes
  resources :forums do
    resources :comments, only: [:create, :destroy]
  end
  
  devise_for :users
  get 'home/home'

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/programa.rb
class Programa < ApplicationRecord
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  before_action :set_programa, only: [:show, :edit, :update, :destroy]

  # GET /programas
  # GET /programas.json
  def index
    @programas = Programa.all
  end

  # GET /programas/1
  # GET /programas/1.json
  def show
  end

  # GET /programas/new
  def new
    @programa = Programa.new
  end

  # GET /programas/1/edit
  def edit
  end

  # POST /programas
  # POST /programas.json
  def create
    @programa = Programa.new(programa_params)

    respond_to do |format|
      if @programa.save
        format.html { redirect_to @programa, notice: 'Programa was successfully created.' }
        format.json { render :show, status: :created, location: @programa }
      else
        format.html { render :new }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programas/1
  # PATCH/PUT /programas/1.json
  def update
    respond_to do |format|
      if @programa.update(programa_params)
        format.html { redirect_to @programa, notice: 'Programa was successfully updated.' }
        format.json { render :show, status: :ok, location: @programa }
      else
        format.html { render :edit }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programas/1
  # DELETE /programas/1.json
  def destroy
    @programa.destroy
    respond_to do |format|
      format.html { redirect_to programas_url, notice: 'Programa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programa
      @programa = Programa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def programa_params
      params.fetch(:programa, {})
    end
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/programas/_form.html.erb
<%= form_with(model: programa, local: true) do |form| %>
  <% if programa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programa.errors.count, "error") %> prohibited this programa from being saved:</h2>

      <ul>
      <% programa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programas/edit.html.erb
<h1>Editing Programa</h1>

<%= render 'form', programa: @programa %>

<%= link_to 'Show', @programa %> |
<%= link_to 'Back', programas_path %>

app/views/programas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programas.each do |programa| %>
      <tr>
        <td><%= link_to 'Show', programa %></td>
        <td><%= link_to 'Edit', edit_programa_path(programa) %></td>
        <td><%= link_to 'Destroy', programa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programa', new_programa_path %>

app/views/programas/new.html.erb
<h1>New Programa</h1>

<%= render 'form', programa: @programa %>

<%= link_to 'Back', programas_path %>

app/views/programas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_programa_path(@programa) %> |
<%= link_to 'Back', programas_path %>