config/routes.rb
Rails.application.routes.draw do
  resources :estudia
  resources :trabajas
  resources :programas
  resources :aprendes
  resources :forums do
    resources :comments, only: [:create, :destroy]
  end
  
  devise_for :users
  get 'home/home'

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aprende.rb
class Aprende < ApplicationRecord
end

app/controllers/aprendes_controller.rb
class AprendesController < ApplicationController
  before_action :set_aprende, only: [:show, :edit, :update, :destroy]

  # GET /aprendes
  # GET /aprendes.json
  def index
    @aprendes = Aprende.all
  end

  # GET /aprendes/1
  # GET /aprendes/1.json
  def show
  end

  # GET /aprendes/new
  def new
    @aprende = Aprende.new
  end

  # GET /aprendes/1/edit
  def edit
  end

  # POST /aprendes
  # POST /aprendes.json
  def create
    @aprende = Aprende.new(aprende_params)

    respond_to do |format|
      if @aprende.save
        format.html { redirect_to @aprende, notice: 'Aprende was successfully created.' }
        format.json { render :show, status: :created, location: @aprende }
      else
        format.html { render :new }
        format.json { render json: @aprende.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aprendes/1
  # PATCH/PUT /aprendes/1.json
  def update
    respond_to do |format|
      if @aprende.update(aprende_params)
        format.html { redirect_to @aprende, notice: 'Aprende was successfully updated.' }
        format.json { render :show, status: :ok, location: @aprende }
      else
        format.html { render :edit }
        format.json { render json: @aprende.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aprendes/1
  # DELETE /aprendes/1.json
  def destroy
    @aprende.destroy
    respond_to do |format|
      format.html { redirect_to aprendes_url, notice: 'Aprende was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aprende
      @aprende = Aprende.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aprende_params
      params.fetch(:aprende, {})
    end
end

app/helpers/aprendes_helper.rb
module AprendesHelper
end

app/views/aprendes/_form.html.erb
<%= form_with(model: aprende, local: true) do |form| %>
  <% if aprende.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aprende.errors.count, "error") %> prohibited this aprende from being saved:</h2>

      <ul>
      <% aprende.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aprendes/edit.html.erb
<h1>Editing Aprende</h1>

<%= render 'form', aprende: @aprende %>

<%= link_to 'Show', @aprende %> |
<%= link_to 'Back', aprendes_path %>

app/views/aprendes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aprendes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aprendes.each do |aprende| %>
      <tr>
        <td><%= link_to 'Show', aprende %></td>
        <td><%= link_to 'Edit', edit_aprende_path(aprende) %></td>
        <td><%= link_to 'Destroy', aprende, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aprende', new_aprende_path %>

app/views/aprendes/new.html.erb
<h1>New Aprende</h1>

<%= render 'form', aprende: @aprende %>

<%= link_to 'Back', aprendes_path %>

app/views/aprendes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_aprende_path(@aprende) %> |
<%= link_to 'Back', aprendes_path %>