config/routes.rb
Rails.application.routes.draw do
  resources :estudia
  resources :trabajas
  resources :programas
  resources :aprendes
  resources :forums do
    resources :comments, only: [:create, :destroy]
  end
  
  devise_for :users
  get 'home/home'

  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
   else
      can :read, :all
      can [:destroy, :create, :update], [Forum, Comment], user_id: user.id
      
   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aprende.rb
class Aprende < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :forum
end

app/models/estudium.rb
class Estudium < ApplicationRecord
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
end

app/models/programa.rb
class Programa < ApplicationRecord
end

app/models/trabaja.rb
class Trabaja < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments, dependent: :destroy

  enum role: [:admin, :visit]
end

app/controllers/estudia_controller.rb
class EstudiaController < ApplicationController
  #before_action :set_estudium, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /estudia
  # GET /estudia.json
  def index
    @estudia = Estudium.all
  end

  # GET /estudia/1
  # GET /estudia/1.json
  def show
  end

  # GET /estudia/new
  def new
    @estudium = Estudium.new
  end

  # GET /estudia/1/edit
  def edit
  end

  # POST /estudia
  # POST /estudia.json
  def create
    @estudium = Estudium.new(estudium_params)
    @forum.user = current_user
    respond_to do |format|
      if @estudium.save
        format.html { redirect_to @estudium, notice: 'Estudium was successfully created.' }
        format.json { render :show, status: :created, location: @estudium }
      else
        format.html { render :new }
        format.json { render json: @estudium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudia/1
  # PATCH/PUT /estudia/1.json
  def update
    respond_to do |format|
      if @estudium.update(estudium_params)
        format.html { redirect_to @estudium, notice: 'Estudium was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudium }
      else
        format.html { render :edit }
        format.json { render json: @estudium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudia/1
  # DELETE /estudia/1.json
  def destroy
    @estudium.destroy
    respond_to do |format|
      format.html { redirect_to estudia_url, notice: 'Estudium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudium
      @estudium = Estudium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudium_params
      params.require(:estudium).permit(:nombre, :categoria, :descripcion, :ubicacion, :sede, :carreras, :modo, :nivel)
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  #before_action :set_forum, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:new, :create, :edit, :destr
  load_and_authorize_resource

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @comments = @forum.comments
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    @forum.user = current_user
    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forum_params
      params.require(:forum).permit(:name, :description, :photo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aprendes_helper.rb
module AprendesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/estudia_helper.rb
module EstudiaHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/trabajas_helper.rb
module TrabajasHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" <%= link_to "Aprende-programa", root_path %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" class="nav-link" <%= link_to "Aprende", aprendes_path %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Programa", programas_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Estudia", estudia_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Trabaja", trabajas_path %></a>
        </li>
        <li class="nav-item dropdown">
        <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Cuenta
          </a>
          <% else %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Acceso
          </a>
          <% end %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <a class="dropdown-item" <%= link_to "Editar", edit_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to "salir", destroy_user_session_path, method: :delete %></a>
            <% else %>
              <a class="dropdown-item" <%= link_to "Ingresar", new_user_session_path %></a>
              <a class="dropdown-item" <%= link_to "Crear cuenta", new_user_registration_path %></a>
            <% end %>
          </div>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Foro", forums_path %></a>
          </li>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
          <a class="nav-link disabled" tabindex="-1" aria-disabled="true" href="#" ><%= current_user.email %></a>
          <% end %>
        </li>
        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aprendeprograma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    <% if alert.present? %>
    <div class="alert"><%= alert %></div>
    <p class="notice"><%= notice %></p>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>